
@url = http://localhost:3000



### 1 - Listar todos os treinos 
GET {{url}}/treinos





### 2 - Criar um treino             
POST {{url}}/treinos
Content-Type: application/json

{
    "nome": "Peito e triceps",
    "duracao": 90
}





### 3 - Criar outro treino  
POST {{url}}/treinos
Content-Type: application/json

{
    "nome": "Costas e biceps",
    "duracao": 12
}





### 4 - Buscar o treino 1 
GET {{url}}/treinos/1





### 5 - Buscar um treino que nao existe
GET {{url}}/treinos/99999





### 6 - Criar sem o nome                  
POST {{url}}/treinos
Content-Type: application/json

{
    "duracao": 30
}


### 7 - Criar com duracao invalida        
POST {{url}}/treinos
Content-Type: application/json

{
    "nome": "Corrida",
    "duracao": -5
}


### 8 - Alterar o treino 1           
PUT {{url}}/treinos/1
Content-Type: application/json

{
    "nome": "Peito, triceps e ombro",
    "duracao": 75
}


### 9 - Alterar um treino que nao existe   
PUT {{url}}/treinos/99999
Content-Type: application/json

{
    "nome": "Qualquer",
    "duracao": 10
}





### 10 - Apagar o treino 2
DELETE {{url}}/treinos/2





### 11 - Apagar um treino que nao existe 
DELETE {{url}}/treinos/99999





### 12 - Listar de novo pra conferir 
GET {{url}}/treinos
